In [8]:
import requests
import json
import pandas as pd

In [9]:
from apiExchange import api_key

In [10]:
CPI_Data = pd.read_csv("CorruptionPerceptionIndex.csv")
CPI_Data.head()

,Country,ISO3,Region,CPI score 2018,Rank 2018,Sources 2018,Standard error 2018,CPI score 2017,Rank 2017,Sources 2017,...,Standard error 2015,CPI score 2014,Sources 2014,Standard error 2014,CPI Score 2013,Sources 2013,Standard error 2013,CPI Score 2012,Sources 2012,Standard error 2012
0,Denmark,DNK,WE/EU,88,1,8,2.63,88,2,8,...,2.16,92.0,7.0,2.04,91.0,7.0,2.2,90.0,7.0,2.0
1,New Zealand,NZL,AP,87,2,8,2.44,89,1,8,...,2.32,91.0,7.0,2.28,91.0,7.0,2.3,90.0,7.0,2.2
2,Finland,FIN,WE/EU,85,3,8,2.74,85,3,8,...,1.77,89.0,7.0,2.05,89.0,7.0,1.7,90.0,7.0,3.0
3,Singapore,SGP,AP,85,3,9,1.98,84,6,9,...,2.02,84.0,8.0,1.75,86.0,9.0,2.3,87.0,9.0,2.1
4,Sweden,SWE,WE/EU,85,3,8,2.02,84,6,8,...,1.71,87.0,7.0,3.41,89.0,7.0,2.3,88.0,7.0,1.9

In [11]:
CPI_Data["Currency ID"] = ""
CPI_Data["Currency Value in USD"] = ""
USD = "USD_"
base_url="https://free.currencyconverterapi.com/api/v6/currencies?apiKey=" + api_key
CPI_Data.head()

,Country,ISO3,Region,CPI score 2018,Rank 2018,Sources 2018,Standard error 2018,CPI score 2017,Rank 2017,Sources 2017,...,Sources 2014,Standard error 2014,CPI Score 2013,Sources 2013,Standard error 2013,CPI Score 2012,Sources 2012,Standard error 2012,Currency ID,Currency Value in USD
0,Denmark,DNK,WE/EU,88,1,8,2.63,88,2,8,...,7.0,2.04,91.0,7.0,2.2,90.0,7.0,2.0,,
1,New Zealand,NZL,AP,87,2,8,2.44,89,1,8,...,7.0,2.28,91.0,7.0,2.3,90.0,7.0,2.2,,
2,Finland,FIN,WE/EU,85,3,8,2.74,85,3,8,...,7.0,2.05,89.0,7.0,1.7,90.0,7.0,3.0,,
3,Singapore,SGP,AP,85,3,9,1.98,84,6,9,...,8.0,1.75,86.0,9.0,2.3,87.0,9.0,2.1,,
4,Sweden,SWE,WE/EU,85,3,8,2.02,84,6,8,...,7.0,3.41,89.0,7.0,2.3,88.0,7.0,1.9,,

In [ ]:
for index, row in CPI_Data.iterrows():
    #get country from df
    country = row["Country"]
    query_url = base_url
 
    response = requests.get(query_url).json()
    results = response

In [ ]:
https://free.currencyconverterapi.com
    currencyId